name: Publish application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore and Build
        uses: ./.github/actions/build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Lint
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/actions/test

  approval:
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Approval required
        uses: ./.github/actions/approval
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN}}"
          TITLE: 'Publish build'
          BODY: 'Approval required to publish'

  deploy:
    runs-on: ubuntu-latest
    needs: [approval]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Artifacts
        uses: ./.github/actions/deploy
